robot:
  _target_: gello.robots.sim_robot.MujocoRobotServer
  xml_path: "third_party/mujoco_menagerie/universal_robots_ur5e/ur5e.xml"
  gripper_xml_path: "third_party/mujoco_menagerie/robotiq_2f85/2f85.xml"
  host: "127.0.0.1"
  port: 6001

agent:
  _target_: gello.agents.spacemouse_agent.SpacemouseAgent
  robot_type: ur5
  invert_button: true
hz: 30
