robot:
  _target_: gello.robots.ur.URRobot
  robot_ip: 192.168.50.20
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTAKRKDB-if00-port0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [1.57, 6.283, 3.142, 4.712, 6.283, 3.142]
    joint_signs: [1, 1, -1, 1, 1, 1]
    gripper_config: [7, 192, 150]
  start_joints: [0.0, -1.57, 1.57, -1.57, -1.57, 0.0, 1.0]
hz: 30

# Camera configuration (optional - remove this section to disable cameras)
# Connects to ZMQ camera servers started by launch_camera_nodes.py
# Camera servers auto-assign: first camera → port 5000, second camera → port 5001
cameras:
  image:
    port: 5000
    host: 127.0.0.1
  wrist_image:
    port: 5001
    host: 127.0.0.1
